#!/bin/sh
if [ ! -x scripts/checkpatch.pl ]; then
    echo >&2 "can't find scripts/checkpatch.pl; are you in the right directory?"
    exit 1
fi
for rev in $(git rev-list "$@"); do
    echo "checking commmit $rev ('$(git log --pretty=%s $rev -1)')"
    git format-patch --stdout $rev -1 | scripts/checkpatch.pl -
    echo
done
