#!/bin/sh

# Install all firmware from a checkout of linux-firmware.git

sed -n '/^File: / { s/^File: //; s/ .*//; p }' < WHENCE | \
while read file; do
    if [ -f /lib/firmware/"$file" ]; then
	if diff -q "$file" /lib/firmware/"$file"; then
	    # no change
	    continue
	fi
      	ln /lib/firmware/"$file" /lib/firmware/"$file".old
    fi
    mkdir -p /lib/firmware/"$(dirname "$file")"
    install -m644 "$file" /lib/firmware/"$file"
done
