/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/* X-SPDX-Copyright-Text: Copyright (C) 2023, Advanced Micro Devices, Inc. */

#ifndef CI_DRIVER_EFAB_HARDWARE_EF10CT_H
#define CI_DRIVER_EFAB_HARDWARE_EF10CT_H

/* Hardware defs go here, ideally auto-generated. */

#define	EFCT_TEST_ROLLOVER_LBN 53
#define	EFCT_TEST_ROLLOVER_WIDTH 1
#define	EFCT_TEST_SENTINEL_VALUE_LBN 52
#define	EFCT_TEST_SENTINEL_VALUE_WIDTH 1
#define	EFCT_TEST_PAGE_ADDRESS_LBN 0
#define	EFCT_TEST_PAGE_ADDRESS_WIDTH 52

/* rx event bit field definitions */
#define	EFCT_TEST_RX_EVENT_NUM_PACKETS_LBN 0
#define	EFCT_TEST_RX_EVENT_NUM_PACKETS_WIDTH 16

#define	EFCT_TEST_RX_EVENT_LABEL_LBN 16
#define	EFCT_TEST_RX_EVENT_LABEL_WIDTH 8

#define	EFCT_TEST_RX_EVENT_RSVD_LBN 24
#define	EFCT_TEST_RX_EVENT_RSVD_WIDTH 33

#define	EFCT_TEST_RX_EVENT_ROLLOVER_LBN 57
#define	EFCT_TEST_RX_EVENT_ROLLOVER_WIDTH 1

#define	EFCT_TEST_RX_EVENT_FLOW_LOOKUP_LBN 58
#define	EFCT_TEST_RX_EVENT_FLOW_LOOKUP_WIDTH 1

#define	EFCT_TEST_RX_EVENT_PHASE_LBN 59
#define	EFCT_TEST_RX_EVENT_PHASE_WIDTH 1

#define	EFCT_TEST_RX_EVENT_TYPE_LBN 60
#define	EFCT_TEST_RX_EVENT_TYPE_WIDTH 4

#endif
