
/* Get the build profile */
#include <ci/internal/transport_config_opt.h>

/* Include autogenerated macros */
#include "lib/ciul/onload_version.h"

const char onload_product[] = ONLOAD_PRODUCT;
const char onload_copyright[] = ONLOAD_COPYRIGHT;
const char* const onload_version = ONLOAD_VERSION;
const char onload_short_version[] = ONLOAD_SHORT_VERSION;
