
/* Include autogenerated macros */
#include "onload_version.h"

const char* const onload_product = ONLOAD_PRODUCT;
const char* const onload_copyright = ONLOAD_COPYRIGHT;
const char* const onload_version = ONLOAD_VERSION;
const char* const onload_short_version = ONLOAD_SHORT_VERSION;
