/* SPDX-License-Identifier: GPL-2.0 */
/* X-SPDX-Copyright-Text: (c) Copyright 2017-2020 Xilinx, Inc. */
#ifndef __CI_INTERNAL_OO_VI_FLAGS_H__
#define __CI_INTERNAL_OO_VI_FLAGS_H__

#define OO_VI_FLAGS_PIO_EN 0x1
#define OO_VI_FLAGS_RX_HW_TS_EN 0x2
#define OO_VI_FLAGS_TX_HW_LOOPBACK_EN 0x4
#define OO_VI_FLAGS_TX_HW_TS_EN 0x8
#define OO_VI_FLAGS_CTPIO_EN 0x10
#define OO_VI_FLAGS_PLUGIN_IO_EN 0x20
#define OO_VI_FLAGS_TX_CTPIO_ONLY 0x40
#define OO_VI_FLAGS_RX_SHARED 0x80
#define OO_VI_FLAGS_HW_MULTICAST_REPLICATION 0x100

#endif /* __CI_INTERNAL_OO_VI_FLAGS_H__ */
